# Generated by Django 6.0.4 on 2026-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_nav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
