# Generated by Django 6.0.4 on 2026-05-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor_nav', '0002_edge_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='poi_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
